podTemplate(yaml: '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
  - name: git
    image: alpine/git:latest
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
''' 
) {
    node(POD_LABEL) {
        container('git') {
            stage('Print Env') {
                sh '''
                  echo $BUILD_NUMBER
                  echo $GIT_URL
                  echo $GIT_BRANCH
                '''
            }
        }
    }
   
}