podTemplate(yaml: '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
  - name: git
    image: alpine/git:latest
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
''' 
) {
    node(POD_LABEL) {
        container('git') {
            stage('Print Env') {
                sh '''
                  echo "build number: ${env.BUILD_NUMBER}"
                  echo "git url: ${env.GIT_URL}"
                  echo "git branch: ${env.GIT_BRANCH}"
                '''
            }
        }
    }
   
}