String determineRepoName() {
    return scm.getUserRemoteConfigs()[0].getUrl().tokenize('/')[3].split("\\.")[0]
}

def repoUrl = scm.getUserRemoteConfigs()[0].getUrl()
def repoName = determineRepoName(repoUrl)
env.owner = "Nishanth"
podTemplate(yaml: '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
  - name: git
    image: alpine/git:latest
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
''' 
) {
    node(POD_LABEL) {
        container('git') {
            stage('Print Env') {
                checkout scm

                sh """
                  echo "owner: \$owner"
                  echo "repoUrl: ${repoUrl}"
                  echo "repoName: ${repoName}"
                """
            }
        }
    }
   
}